### ISSUE TITLE
About model details

### ISSUE THREAD

**Issue by tomato18463** [fhchl/quant-comp-ls-mod-ica22#1]
Hi,

Thanks very much for sharing your work! I am interested in the work and trying to develop my own project based on it, but I have little knowledge about loudspeaker models the code implemented. I wonder if you could provide me some information on where to find detailed derivations of the loudspeaker frequency response like https://github.com/fhchl/quant-comp-ls-mod-ica22/blob/publish-code-orphan/src/model.py#L191?

Thank you very much!

**Comment by fhchl** [comment]
Glad it is of use to you! 

Is your question specific about loudspeaker transfer-functions? Then I would recommend a look into [Beranek and Mellows book](https://www.amazon.com/Acoustics-Sound-Fields-Transducers-Vibration/dp/0128152273) (if you can find a copy) and a look into the [paper](https://github.com/fhchl/quant-comp-ls-mod-ica22/blob/publish-code-orphan/paper.pdf) for setting up the linear ODE model.

If you are thinking about general systems, then you would transform your linear ODEs into Laplace domain and solve for your output as a function of the input. Most control and linear systems books should describe how to do this.
