### ISSUE TITLE
Unable to run the code on Windows

### ISSUE THREAD

**Issue by rgmey** [fhchl/quant-comp-ls-mod-ica22#4]
Hi, 

I've been trying to run your project on windows using my own data, the library dependencies were crazy( I was not able to install all of them using the "environment.yml" file. Anyways, I finally managed to get the code running in Google Colab, which is somehow able to install the "JAXLIB=0.3.15", but when I try to run the same code and install the libraries on my local machine(windows), I get the error below:
pip install jaxlib==0.3.15
"ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.15 (from versions: 0.3.24, 0.3.25, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19)
ERROR: No matching distribution found for jaxlib==0.3.15"

I'm not the expert on installing packages but I was wondering if there is a way around the issue? like changing the version of Jax to be able to use one of the compatible versions of Jaxlib which are available in windows?
Any clues are highly appreciated, thanks for taking the time in advance.

**Comment by fhchl** [comment]
Hi there! jaxlib was not officially supported on windows until 0.3.24. As described in the readme, there is an `environment_windows.yml` that installs the unofficial windows build. 

Regarding your comment on the "crazy" dependencies, I just deleted the version specifications in the windows environment file, which should make it easier to install. Let me know if this works for you.
